baseURL = "https://about.dragosboca.eu/"
languageCode = "en-us"

title = "Dragos Boca"
theme = ""


[deployment]
    [[deployment.targets]]
    name = "haws"
    URL = "s3://haws-hugo-dragosboca-eu-bucket?region=eu-west-1&prefix=CV/"
    cloudFrontDistributionID = "E2AJH0F5D8GI9O"


[params]
    author = "Dragos Boca"
    description = "Resume"

    primaryColor = "#202020"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Dragos Boca"
        tagline = "DevOps - Infrastructure Developer"
        avatar = "CV-picture.jpg"

    [params.contact]
        enable = true
        location = "Bucharest, Romania"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+40 728 001 186"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "dragos.boca@gmail.com"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "www.yourwebsite.com"

    [params.skills]
        enable = true
        enable_ratings = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Terraform"
        rating = 5
        [[params.skills.list.items]]
        details = "Ansible"
        rating = 5
        [[params.skills.list.items]]
        details = "Helm"
        rating = 5
        [[params.skills.list.items]]
        details = "AWS"
        rating = 4
        [[params.skills.list.items]]
        details = "Golang"
        rating = 3
        [[params.skills.list.items]]
        details = "Python"
        rating = 3
        [[params.skills.list.items]]
        details = "Bash"
        rating = 4
        [[params.skills.list.items]]
        details = "Perl"
        rating = 3
        [[params.skills.list.items]]
        details = "Git"
        rating = 0
        [[params.skills.list.items]]
        details = "GitLab"
        rating = 0
        [[params.skills.list.items]]
        details = "ArgoCD"
        rating = 0

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Electrical Engineer"
        university = "\"Politehnica\" University of Bucharest"
        dates = "1996 - 1999"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Romanian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Trecking"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        
        # text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "System Reliability Engineer"
        dates = "Jully 2021 - Present"
        company = "Siemens AG - Freelancer"
        details = "With Siemens I participated in multiple projects, all on AWS cloud and EKS; the most notable beeing"
        [[ params.experience.list.items]]
        details = "Deploiyng and maintaining a Hyperledger Fabric network on multiple EKS clusters with terraform and Ansible and also writing Kubernetes Operators in Go and Ansible"
        [[ params.experience.list.items]]
        details = "Building a CI/CD pipeline for a Windows application in an EKS cluster using GitLab CI"
        [[ params.experience.list.items]]
        details = "A CI/CD Pipeline that also uses Gitlab CI and for a long term project"
        [[params.experience.list.techstack]]
        item = "AWS"
        [[params.experience.list.techstack]]
        item = "Kubernetes"
        [[params.experience.list.techstack]]
        item = "EKS"
        [[params.experience.list.techstack]]
        item = "Helm"
        [[params.experience.list.techstack]]
        item = "Go"
        [[params.experience.list.techstack]]
        item = "Ansible"
        [[params.experience.list.techstack]]
        item = "Hyperledger Fabric"
       
        [[params.experience.list]]
        title = "System Reliability Engineer"
        dates = "Oct 2018 – May 2021"
        company = "Adobe"
        details = "Live migrate a large, geo-distributed, group of monolith applications from on-premisses datacenter to Kubernetes EKS clusters in AWS"
        [[params.experience.list.items]]
        details = "I designed the architecture for the new cloud-based infrastructure for the application. I also chose the tech stack and contributed to the design guidelines for the code responsible for the infrastructure."
        [[params.experience.list.items]]
        details = "I also contributed to the monitoring and logging infrastructure - using Prometheus respectively fluentd - and fine-tuned the components to ensure maximum performance and stability."
        [[params.experience.list.items]]
        details = "I contributed to most of the code for the infrastructure. Together with the engineering team, we established procedures and response actions to various events generated by infrastructure or applications."
        [[params.experience.list.items]]
        details = "I designed and implemented the DNS solution for the application, including a geo-DNS routing solution with complex weighted and latency based rules and records."
        [[params.experience.list.items]]
        details = "I participated in on-call rotation and on-call activities, including post-mortem analysis and root-cause analysis of the issues detected."
        [[params.experience.list.techstack]]
        item = "AWS"
        [[params.experience.list.techstack]]
        item = "Kubernetes"
        [[params.experience.list.techstack]]
        item = "EKS"
        [[params.experience.list.techstack]]
        item = "Helm"
        [[params.experience.list.techstack]]
        item = "Go"
        [[params.experience.list.techstack]]
        item = "Ansible"
        [[params.experience.list.techstack]]
        item = "Terraform"
        [[params.experience.list.techstack]]
        item = "Prometheus"
        [[params.experience.list.techstack]]
        item = "Fluentd"


        [[params.experience.list]]
        title = "System Reliability Engineer"
        dates = "Nov 2017 – Sep 2018"
        company = "OwnZones"
        details = "Migrate a microservices project from classical EC2 based infrastructure to Kubernetes"
        [[params.experience.list.items]]
        details = "I configured several Kubernetes clusters (different clusters for production-like environments and development environments) located in two AWS accounts (one for production and one for development) using Kops and Helm - including monitoring with Prometheus, logging and alerting (integration with Victorops), cluster autoscaling, custom metrics HPA and integration with Spotinst."
        [[params.experience.list.items]]
        details = "I designed and implemented a CI/CD pipeline starting from CircleCi using Helm, Terraform (for components not hosted in Kubernetes like databases or Redis clusters) and custom deployment scripts."
        [[params.experience.list.techstack]]
        item = "AWS"
        [[params.experience.list.techstack]]
        item = "Kubernetes"
        [[params.experience.list.techstack]]
        item = "Kops"
        [[params.experience.list.techstack]]
        item = "Helm"
        [[params.experience.list.techstack]]
        item = "Go"
        [[params.experience.list.techstack]]
        item = "Terraform"
        [[params.experience.list.techstack]]
        item = "Prometheus"
        [[params.experience.list.techstack]]
        item = "Fluentd"
        
        [[params.experience.list]]
        title = "Devops Consultant"
        dates = "November 2016 - November 2017"
        company = "Endava"
        details = "Migrate development environment from on-premisses infrastructure to cloud infrastructure hosted in AWS. "
        [[params.experience.list.items]]
        details = "I designed the architecture for the cloud infrastructure required to host development infrastructure of several projects in finance/banking domain and also designed a CI/CD pipeline based on Jenkins. The infrastructure was provisioned with Terraform and Ansible and included several stages as well as the ability to provision on-the fly on-demand environments for experimental features. The application was hosted on Oracle WebLogic servers (configured mostly with Ansible and custom shell scripts) and the database was also Oracle DB (managed by AWS)"
        [[params.experience.list.techstack]]
        item = "AWS"
        [[params.experience.list.techstack]]
        item = "Kubernetes"
        [[params.experience.list.techstack]]
        item = "Ansible"
        [[params.experience.list.techstack]]
        item = "Terraform"


        [[params.experience.list]]
        title = "Principal DevOps Engineer"
        dates = "April 2014 - November 2016"
        company = "ORACLE"
        details = "DevOps in a large team responsible of a very demanding and fast paced development product. My primary task is to support, maintain, monitor and improve the dev and QA environments for one of the products of Fusion Applications"
        [[params.experience.list.items]]
        details = "Devlopment of automation for various deployment, maintenance and monitoring processes."
        [[params.experience.list.items]]
        details = "Server and application log analysis and monitoring."
        [[params.experience.list.techstack]]
        item = "Perl"
        [[params.experience.list.techstack]]
        item = "Python"

        [[params.experience.list]]
        title = "DevOps"
        dates = "June 2014 - April 2016"
        company = "SoftVision"
        details = "I participated to several projects involving cloud architecture and cloud applications. Mostly I had to deal with:"
        [[params.experience.list.items]]
	    details = "Development of automation tools to manage and deploy applications, using Ansible and Puppet and custom-made scripts in Python, Bash and Ruby."
        [[params.experience.list.items]]
    	details = "Building and management of  production, development and testing environments on AWS infrastructure, assisting developers in debugging application issues."
        [[params.experience.list.items]]
    	details = "Building of tools and processes to support the infrastructure."
        [[params.experience.list.techstack]]
        item = "AWS"
        [[params.experience.list.techstack]]
        item = "Puppet2"
        [[params.experience.list.techstack]]
        item = "Ansible"
        [[params.experience.list.techstack]]
        item = "Docker"


        [[params.experience.list]]
        title = "Linux System Developer"
        dates = "April 2012 - June 2014"
        company = "1&1 Internet AG"
        details = "Maintenance and monitoring of several on-premises application servers (mostly JBoss) for QA and dev and production environments and also development of a custom automatic provisioning system for load-balancers based of Linux Virtual Server, HA-Proxy and Heartbeat"
        [[params.experience.list.items]]
		details = "Development of new infrastructure applications and frameworks."
        [[params.experience.list.items]]
    	details = "Maintenance and administration of existing infrastructure (mostly applications and frameworks built on top of Debian Linux)."
        [[params.experience.list.techstack]]
        item = "Perl"
        [[params.experience.list.techstack]]
        item = "Python"
        [[params.experience.list.techstack]]
        item = "Ruby"
        [[params.experience.list.techstack]]
        item = "Linux"

        [[params.experience.list]]
        title = "Linux System Developer"
        dates = "June 2014 - April 2015"
        company = "Interactive Systems"
        details = "Custom linux distribution based on Ubuntu"
        [[params.experience.list.items]]
        details = "Development of initiallization and configuration scripts for various Linux services."
        [[params.experience.list.items]]
    	details = "Development of a custom installation software for a Linux distribution."
        [[params.experience.list.items]]
    	details = "Development and maintenance of the QA and dev environments suitable for testing an entire Linux distribution."
        [[params.experience.list.items]]
    	details = "Maintenance and administration of the department servers running RedHat Linux."
        [[params.experience.list.techstack]]
        item = "Perl"
        [[params.experience.list.techstack]]
        item = "Linux"

        [[params.experience.list]]
        title = "System Administrator / Technical support engineer"
        dates = "June 2007 - Jully 2011"
        company = "Joint Venture Aktor Athena"
        details = """
The project I was worked for was \"Waste Water Treatment Plant – Glina\" I had as primary task network and system administration of the on-site network consisting of a large number of workstations, networked printers and two servers running on Fedora Linux. The infrastructure also included several VPN (OpenVPN and PPTP) connecting various location booth  on-site and remote.

I was also working as local technical support and my tasks consisted in:
"""
        [[params.experience.list.items]]
        details = "Analysis and evaluation of third-party designs for electrical installations."
        [[params.experience.list.items]]
        details = "Analysis and evaluation of various offers from subcontractors for designing and execution of electrical installations."
        [[params.experience.list.techstack]]
        item = "Linux"
        [[params.experience.list.techstack]]
        item = "Monitoring"

        [[params.experience.list]]
        title = "Site Engineer (Project Based)"
        dates = "August 2006 - March 2007"
        company = "D&T Industrial Equipment"
        details = "The project I was worked for was \"Kaufland - Barbu Vacarescu\" and I was supervising the design and execution for all the installations in the store."
        [[params.experience.list.items]]
        details = "Management of work schedule and budget of the project"
        [[params.experience.list.items]]
        details = "Management of work schedule and budget for works made by subcontractors"
        [[params.experience.list.items]]
        details = "Management of the design team"
        [[params.experience.list.items]]
        details = "Supervision of the execution"

        [[params.experience.list]]
        title = "Head of Design Department"
        dates = "December 2004 - August 2006"
        company = "Helinick"
        details = "Main tasks:"
        [[params.experience.list.items]]
        details = "Head of design department"
        [[params.experience.list.items]]
        details = "Coordinating and supervising the activity of the department"
        [[params.experience.list.items]]
        details = "Designing of weak-currents installations."

        [[params.experience.list]]
        title = "Electrical Installation Designer"
        dates = "October 2003 - December 2004"
        company = "SIMEROM"
        details = "SIMEROM was a subsidiary of an Italian company called SIME that have contracts with major companyes in Oil&Gas and energy production companies (like ENI, ALSTOM and TECHNIOMONT). I worked as a senior designer engineer booth in Bucharest offices and in Milano."

        [[params.experience.list]]
        title = "Junior Electrical Installation Designer"
        dates = "Jully 2001 - October 2003"
        company = "TIAB SA"
        details = """
TIAB was a well known Romanian company that has been purchased by Group VINCY and had more than 50 years experience in installations and was one of the major companies with a large field of services that includes technical and technological design, erection and comissioniong of installations for civil and industrial objectives and also have a large number of projects in energy production, oil&gas industry, food industry and many others.

During the time when I was working for TIAB I was involved mostly in detail designing for various electrical installations.
"""

        [[params.experience.list]]
        title = "IT Support / Maintenance Engineer"
        dates = "August 2000 - July 2001"
        company = "ZIROM"
        details = "I was involved in the maintenance of electrical installations of the plant and also in maintenance of various electrical equipment. I also have been working as Network Administrator of the company's network having several servers (mostly running RedHat Linux) and a large number of workstations with booth Linux and Windows OS."



    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/dragosboca"
        title = "dragosboca"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/dragosboca"
        title = "dragosboca"
        # [[params.social.list]]
        # icon = "fab fa-twitter-square"
        # url = "//twitter.com/username"
        # title = "@username"
